name: Deploy to Azure Container Instances

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  DOCKER_IMAGE_NAME: mandelazz-backend
  AZURE_CONTAINER_GROUP: mandelazz-container
  AZURE_RESOURCE_GROUP: myResourceGroup
  AZURE_CONTAINER_NAME: mandelazz-api
  AZURE_LOCATION: eastus

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mandelazz:latest

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name $AZURE_CONTAINER_NAME \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/mandelazz:latest \
            --dns-name-label mandelazz-api-label \
            --ports 80 443 \
            --location $AZURE_LOCATION \
            --restart-policy OnFailure \
            --os-type Linux
