name: Deploy to DockerHub and Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build and Tag Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/mandelazz:$IMAGE_TAG .
          docker tag $DOCKERHUB_USERNAME/mandelazz:$IMAGE_TAG $DOCKERHUB_USERNAME/mandelazz:latest

      - name: Push Docker Image to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $DOCKERHUB_USERNAME/mandelazz:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/mandelazz:latest

  deploy-to-railway:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensures this job runs after the Docker image is pushed

    steps:
      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          IMAGE_TAG: ${{ github.sha }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          curl -X POST "https://backboard.railway.app/graphql/v2" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
            -d '{
              "query": "mutation Deploy($service: String!, $image: String!) {
                deployService(serviceId: $service, image: $image) { id }
              }",
              "variables": {
                "service": "'"$SERVICE_ID"'",
                "image": "'"$DOCKERHUB_USERNAME"'/mandelazz:'"$IMAGE_TAG"'"
              }
            }'
  # run-tests:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run tests
  #       run: npm test

