name: Deploy to Azure Container Instances

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  DOCKER_IMAGE_NAME: mandelazz-backend
  AZURE_CONTAINER_GROUP: mandelazz-container
  AZURE_RESOURCE_GROUP: mandelazz-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kevinejiofor/mandelazz:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          dns-name-label: mandelazz-backend-${{ github.run_number }}
          image: kevinejiofor/mandelazz:latest
          name: mandelazz-container
          location: 'East US'
          cpu: 1
          memory: 1.5
          ports: '3030'
          environment-variables: |
            NODE_ENV=${{ secrets.NODE_ENV || 'production' }}
            MONGO_URI=${{ secrets.MONGO_URI || 'mongodb://localhost:27017/default' }}
            JWT_SECRET=${{ secrets.JWT_SECRET || 'gdgfghdhdhdhdhdggdtetreghrehgwehiuewiujqwbdshsdhhdsbsdhghsddhsghgcbeggdagsgsaghasghdgdqwedrftgbvcxzsa' }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET || 'fdkjfdhbsdbhewbdsjlhuyfrtdjyuiokmlnnhjhbbnmjkkhewijewhwehbdvcvcdsvvcwjwejbkewjnwbeweeqwddxcccccxv' }}
            EMAIL_USER=${{ secrets.EMAIL_USER || 'ejioforkelvin@gmail.com' }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS || 'pbmg uiqf ogky gwus' }}
            PORT=3030
            SOCKET_PORT=3030
            PAYSTACK_BASE_URL=${{ secrets.PAYSTACK_BASE_URL || 'https://api.paystack.co' }}
            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME || 'deop6nsbr' }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY || '529847672862236' }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET || 'ai8yfbUHCWFG2tdI_hO577wLC_0' }}
            PAYSTACK_SECRET_KEY=${{ secrets.PAYSTACK_SECRET_KEY || 'sk_test_eb68af8c15c1b62f52fdaad721ff213202369c08' }}
